"use client";

import { useState } from "react";
import { Sparkles, RefreshCw, MessageSquare, FileText, Download, Check, Terminal } from "lucide-react";
import { motion } from "framer-motion";
import confetti from "canvas-confetti";
import Tilt from "react-parallax-tilt";
import { CaptionOutput } from "../data/prompts";
import ResultCard from "./ResultCard";
import AILoader from "./AILoader";

const TONES = [
  "Story / Personal Vibe",
  "Authority / Expert Vibe",
  "Funny / Sarcastic Vibe",
  "Aesthetic / Relaxed",
];

const PLATFORMS = [
  "Instagram",
  "TikTok",
  "YouTube Shorts",
  "LinkedIn",
  "X (Twitter)",
];

export default function CaptionGenerator() {
  const [topic, setTopic] = useState("");
  const [tone, setTone] = useState("Story / Personal Vibe");
  const [platform, setPlatform] = useState("Instagram");
  
  const [apiLoading, setApiLoading] = useState(false);
  const [showAILoader, setShowAILoader] = useState(false);
  const [pendingResults, setPendingResults] = useState<CaptionOutput | null>(null);
  const [results, setResults] = useState<CaptionOutput | null>(null);
  const [regenerating, setRegenerating] = useState(false);
  
  const [exported, setExported] = useState(false);

  const loadPreset = () => {
    setTopic("Morning Coffee Routine");
    setTone("Funny / Sarcastic Vibe");
    setPlatform("Instagram");
  };

  const handleGenerate = async (e?: React.FormEvent, isRegen = false) => {
    if (e) e.preventDefault();
    if (!topic) return;

    if (isRegen) {
      setRegenerating(true);
    } else {
      setApiLoading(true);
      setShowAILoader(true);
      setResults(null);
      setPendingResults(null);
    }

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          tool: "captions",
          input: {
            topic,
            tone,
            platform,
          },
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate captions");
      }

      const data = await response.json();
      
      if (isRegen) {
        setResults(data.result);
        confetti({
          particleCount: 50,
          spread: 60,
          origin: { y: 0.8 }
        });
      } else {
        setPendingResults(data.result);
      }
    } catch (err) {
      console.error("Error generating captions: ", err);
      setShowAILoader(false);
    } finally {
      setApiLoading(false);
      setRegenerating(false);
    }
  };

  const handleLoaderComplete = () => {
    if (pendingResults) {
      setResults(pendingResults);
      setShowAILoader(false);
      
      confetti({
        particleCount: 100,
        spread: 80,
        origin: { y: 0.6 }
      });
    }
  };

  // Export captions to file
  const handleExportText = () => {
    if (!results) return;
    const fileContent = `--- CAPTION OPTIONS ---
Topic Concept: ${topic}
Tone Preference: ${tone}
Platform: ${platform}

[OPTION 1 — STORY STYLE]
${results.storyStyle}

[OPTION 2 — AUTHORITY STYLE]
${results.authorityStyle}

[OPTION 3 — FUNNY STYLE]
${results.funnyStyle}

---
Generated by Creator OS | digitalheroesco.com`;

    const blob = new Blob([fileContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `captions_${topic.toLowerCase().replace(/\s+/g, "_")}.txt`;
    link.click();
    URL.revokeObjectURL(url);

    setExported(true);
    confetti({
      particleCount: 30,
      spread: 40
    });
    setTimeout(() => setExported(false), 2000);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
      {/* Input Form Column */}
      <div className="lg:col-span-5 bg-white/[0.01] border border-white/5 rounded-3xl p-6 lg:p-8 backdrop-blur-xl shadow-2xl bento-card">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2.5">
            <div className="p-2 bg-pink-500/10 rounded-lg border border-pink-500/20 text-pink-400">
              <Terminal className="h-5 w-5" />
            </div>
            <h3 className="font-bold text-sm tracking-widest text-white uppercase font-mono">03 // NARRATIVE ENGINE</h3>
          </div>
          <button
            type="button"
            onClick={loadPreset}
            className="text-xs flex items-center gap-1 text-pink-400 hover:text-pink-300 font-bold transition-colors cursor-pointer font-mono"
          >
            <RefreshCw className="h-3 w-3" /> PRESET
          </button>
        </div>

        <form onSubmit={(e) => handleGenerate(e, false)} className="space-y-5">
          <div>
            <label className="block text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-2 font-mono">
              Topic or Post Concept
            </label>
            <textarea
              rows={3}
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="Describe your photo or video topic (e.g. launching our new workspace template, healthy morning routine)..."
              className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3.5 text-sm text-white placeholder-zinc-600 focus:outline-none focus:border-white/20 transition-all font-sans resize-none"
              required
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-2 font-mono">
                Primary Vibe/Tone
              </label>
              <select
                value={tone}
                onChange={(e) => setTone(e.target.value)}
                className="w-full bg-zinc-900/50 border border-white/5 rounded-xl px-4 py-3.5 text-sm text-white focus:outline-none focus:border-white/20 transition-all"
              >
                {TONES.map((t) => (
                  <option key={t} value={t}>
                    {t}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-2 font-mono">
                Target Platform
              </label>
              <select
                value={platform}
                onChange={(e) => setPlatform(e.target.value)}
                className="w-full bg-zinc-900/50 border border-white/5 rounded-xl px-4 py-3.5 text-sm text-white focus:outline-none focus:border-white/20 transition-all"
              >
                {PLATFORMS.map((p) => (
                  <option key={p} value={p}>
                    {p}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <button
            type="submit"
            disabled={apiLoading || showAILoader || regenerating || !topic}
            className="w-full mt-6 bg-white hover:bg-zinc-200 disabled:bg-zinc-800/40 disabled:text-zinc-600 disabled:cursor-not-allowed text-black font-bold py-4 px-4 rounded-xl shadow-xl transition-all flex items-center justify-center gap-2 cursor-pointer active:scale-[0.98] font-mono text-xs uppercase tracking-wider"
          >
            <Sparkles className="h-4 w-4" />
            <span>Generate Narratives</span>
          </button>
        </form>
      </div>

      {/* Output Results Column */}
      <div className="lg:col-span-7 space-y-6">
        {showAILoader && (
          <AILoader
            onComplete={handleLoaderComplete}
            isDataReady={!!pendingResults}
          />
        )}

        {!showAILoader && !results && (
          <div className="min-h-[350px] flex flex-col items-center justify-center rounded-3xl border border-white/5 bg-white/[0.005] p-8 text-center backdrop-blur-md shadow-inner">
            <FileText className="h-10 w-10 text-zinc-700 mb-4 animate-pulse" />
            <h4 className="text-zinc-400 font-bold tracking-widest uppercase text-xs font-mono mb-2">Narratives Idle</h4>
            <p className="text-zinc-500 text-xs max-w-sm font-sans mb-5 leading-relaxed font-medium">
              Enter your social concept details on the left and trigger compilation to boot the Narrative Engine text options.
            </p>
            <button
              onClick={loadPreset}
              className="text-[10px] font-mono font-bold px-4 py-2.5 rounded-xl border border-white/10 hover:border-pink-500/30 text-zinc-300 hover:text-white bg-white/5 hover:bg-pink-950/20 transition-all cursor-pointer"
            >
              LOAD_COFFEE_PRESET
            </button>
          </div>
        )}

        {!showAILoader && results && (
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
            className="space-y-6"
          >
            <div className="flex items-center justify-between pb-3 border-b border-white/5">
              <h4 className="font-bold text-white flex items-center gap-2 text-xs font-mono uppercase tracking-wider text-zinc-400">
                <FileText className="h-4 w-4 text-pink-400" /> Compiled Narratives
              </h4>
              
              {/* Batch Export Button */}
              <button
                onClick={handleExportText}
                className="text-[10px] font-mono font-bold flex items-center gap-1.5 rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-zinc-300 hover:text-white hover:bg-white/10 transition-all cursor-pointer"
              >
                {exported ? (
                  <>
                    <Check className="h-3.5 w-3.5 text-emerald-400" />
                    <span className="text-emerald-400">EXPORTED</span>
                  </>
                ) : (
                  <>
                    <Download className="h-3.5 w-3.5" />
                    <span>EXPORT ALL (.TXT)</span>
                  </>
                )}
              </button>
            </div>

            <div className="space-y-4">
              <ResultCard
                title="Story Style"
                content={results.storyStyle}
                onRegenerate={() => handleGenerate(undefined, true)}
                isRegenerating={regenerating}
              />
              <ResultCard
                title="Authority Style"
                content={results.authorityStyle}
                onRegenerate={() => handleGenerate(undefined, true)}
                isRegenerating={regenerating}
              />
              <ResultCard
                title="Funny Style"
                content={results.funnyStyle}
                onRegenerate={() => handleGenerate(undefined, true)}
                isRegenerating={regenerating}
              />
            </div>
          </motion.div>
        )}
      </div>
    </div>
  );
}
