"use client";

import { useState } from "react";
import { Sparkles, RefreshCw, Layers, Radio, Download, Flame, FileText, Check, Terminal } from "lucide-react";
import { motion } from "framer-motion";
import confetti from "canvas-confetti";
import Tilt from "react-parallax-tilt";
import { HookOutput } from "../data/prompts";
import ResultCard from "./ResultCard";
import AILoader from "./AILoader";

const PLATFORMS = [
  "Instagram",
  "TikTok",
  "YouTube Shorts",
  "X (Twitter)",
  "LinkedIn",
];

const TRENDING_HOOKS = [
  { text: "Nobody talks about this skincare hack...", topic: "Skincare Secrets" },
  { text: "I tried this automation for 30 days...", topic: "Python Automation" },
  { text: "The exact framework to make $10k/month...", topic: "SaaS Side Hustle" },
  { text: "Stop scrolling if you write CSS...", topic: "Tailwind Styling Hacks" },
  { text: "Why 99% of creators fail in 30 days...", topic: "Creator consistency" },
];

export default function HookGenerator() {
  const [topic, setTopic] = useState("");
  const [audience, setAudience] = useState("");
  const [platform, setPlatform] = useState("Instagram");
  
  const [apiLoading, setApiLoading] = useState(false);
  const [showAILoader, setShowAILoader] = useState(false);
  const [pendingResults, setPendingResults] = useState<HookOutput | null>(null);
  const [results, setResults] = useState<HookOutput | null>(null);
  const [regenerating, setRegenerating] = useState(false);
  
  const [exported, setExported] = useState(false);

  const loadPreset = () => {
    setTopic("Skincare");
    setAudience("Women");
    setPlatform("Instagram");
  };

  const handleSelectTrending = (item: typeof TRENDING_HOOKS[0]) => {
    setTopic(item.topic);
    setAudience("Creators");
  };

  const handleGenerate = async (e?: React.FormEvent, isRegen = false) => {
    if (e) e.preventDefault();
    if (!topic || !audience) return;

    if (isRegen) {
      setRegenerating(true);
    } else {
      setApiLoading(true);
      setShowAILoader(true);
      setResults(null);
      setPendingResults(null);
    }

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          tool: "hooks",
          input: {
            topic,
            audience,
            platform,
          },
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate hooks");
      }

      const data = await response.json();
      
      if (isRegen) {
        setResults(data.result);
        confetti({
          particleCount: 50,
          spread: 60,
          origin: { y: 0.8 }
        });
      } else {
        setPendingResults(data.result);
      }
    } catch (err) {
      console.error("Error generating hooks: ", err);
      setShowAILoader(false);
    } finally {
      setApiLoading(false);
      setRegenerating(false);
    }
  };

  const handleLoaderComplete = () => {
    if (pendingResults) {
      setResults(pendingResults);
      setShowAILoader(false);
      
      confetti({
        particleCount: 100,
        spread: 80,
        origin: { y: 0.6 }
      });
    }
  };

  // Export hooks to a single file
  const handleExportText = () => {
    if (!results || !results.hooks) return;
    const hooksTextList = results.hooks.map((h, i) => `[Hook #${i + 1}]\n${h}`).join("\n\n");
    const fileContent = `--- VIRAL SOCIAL HOOKS ---
Topic: ${topic}
Audience: ${audience}
Platform: ${platform}

${hooksTextList}

---
Generated by Creator OS | digitalheroesco.com`;

    const blob = new Blob([fileContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `viral_hooks_${topic.toLowerCase().replace(/\s+/g, "_")}.txt`;
    link.click();
    URL.revokeObjectURL(url);

    setExported(true);
    confetti({
      particleCount: 30,
      spread: 40
    });
    setTimeout(() => setExported(false), 2000);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
      
      {/* Input Form Column */}
      <div className="lg:col-span-4 bg-white/[0.01] border border-white/5 rounded-3xl p-6 backdrop-blur-xl shadow-2xl bento-card">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2.5">
            <div className="p-2 bg-indigo-500/10 rounded-lg border border-indigo-500/20 text-indigo-400">
              <Terminal className="h-5 w-5" />
            </div>
            <h3 className="font-bold text-sm tracking-widest text-white uppercase font-mono">02 // ATTENTION ENGINE</h3>
          </div>
          <button
            type="button"
            onClick={loadPreset}
            className="text-xs flex items-center gap-1 text-indigo-400 hover:text-indigo-300 font-bold transition-colors cursor-pointer font-mono"
          >
            <RefreshCw className="h-3 w-3" /> PRESET
          </button>
        </div>

        <form onSubmit={(e) => handleGenerate(e, false)} className="space-y-5">
          <div>
            <label className="block text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-2 font-mono">
              Topic / Concept
            </label>
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g. Skincare, Side Hustle"
              className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3.5 text-sm text-white placeholder-zinc-600 focus:outline-none focus:border-white/20 transition-all font-sans"
              required
            />
          </div>

          <div>
            <label className="block text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-2 font-mono">
              Target Audience
            </label>
            <input
              type="text"
              value={audience}
              onChange={(e) => setAudience(e.target.value)}
              placeholder="e.g. Women, Gen Z, Busy Creators"
              className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3.5 text-sm text-white placeholder-zinc-600 focus:outline-none focus:border-white/20 transition-all font-sans"
              required
            />
          </div>

          <div>
            <label className="block text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-2 font-mono">
              Target Platform
            </label>
            <select
              value={platform}
              onChange={(e) => setPlatform(e.target.value)}
              className="w-full bg-zinc-900/50 border border-white/5 rounded-xl px-4 py-3.5 text-sm text-white focus:outline-none focus:border-white/20 transition-all"
            >
              {PLATFORMS.map((p) => (
                <option key={p} value={p}>
                  {p}
                </option>
              ))}
            </select>
          </div>

          <button
            type="submit"
            disabled={apiLoading || showAILoader || regenerating || !topic || !audience}
            className="w-full mt-6 bg-white hover:bg-zinc-200 disabled:bg-zinc-800/40 disabled:text-zinc-600 disabled:cursor-not-allowed text-black font-bold py-4 px-4 rounded-xl shadow-xl transition-all flex items-center justify-center gap-2 cursor-pointer active:scale-[0.98] font-mono text-xs uppercase tracking-wider"
          >
            <Sparkles className="h-4 w-4" />
            <span>Generate Attention Hooks</span>
          </button>
        </form>
      </div>

      {/* Output Results Grid */}
      <div className="lg:col-span-5 space-y-6">
        {showAILoader && (
          <AILoader
            onComplete={handleLoaderComplete}
            isDataReady={!!pendingResults}
          />
        )}

        {!showAILoader && !results && (
          <div className="min-h-[400px] flex flex-col items-center justify-center rounded-3xl border border-white/5 bg-white/[0.005] p-8 text-center backdrop-blur-md shadow-inner">
            <Layers className="h-10 w-10 text-zinc-700 mb-4 animate-pulse" />
            <h4 className="text-zinc-400 font-bold tracking-widest uppercase text-xs font-mono mb-2">Attention Hooks Idle</h4>
            <p className="text-zinc-500 text-xs max-w-sm font-sans mb-5 leading-relaxed font-medium">
              Boot the Attention Engine on the left or select a trending social copy hook from the sidebar to analyze structures.
            </p>
            <button
              onClick={loadPreset}
              className="text-[10px] font-mono font-bold px-4 py-2.5 rounded-xl border border-white/10 hover:border-indigo-500/30 text-zinc-300 hover:text-white bg-white/5 hover:bg-indigo-950/20 transition-all cursor-pointer"
            >
              LOAD_SKINCARE_PRESET
            </button>
          </div>
        )}

        {!showAILoader && results && results.hooks && (
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
            className="space-y-6"
          >
            <div className="flex items-center justify-between pb-3 border-b border-white/5">
              <h4 className="font-bold text-white flex items-center gap-2 text-xs font-mono uppercase tracking-wider text-zinc-400">
                <Layers className="h-4 w-4 text-indigo-400" /> Compiled Attention Hooks
              </h4>
              
              {/* Batch Export Button */}
              <button
                onClick={handleExportText}
                className="text-[10px] font-mono font-bold flex items-center gap-1.5 rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-zinc-300 hover:text-white hover:bg-white/10 transition-all cursor-pointer"
              >
                {exported ? (
                  <>
                    <Check className="h-3.5 w-3.5 text-emerald-400" />
                    <span className="text-emerald-400">EXPORTED</span>
                  </>
                ) : (
                  <>
                    <Download className="h-3.5 w-3.5" />
                    <span>EXPORT ALL (.TXT)</span>
                  </>
                )}
              </button>
            </div>

            <div className="space-y-3 max-h-[480px] overflow-y-auto pr-2 scrollbar-thin scrollbar-thumb-white/10">
              {results.hooks.map((hook, index) => (
                <ResultCard
                  key={index}
                  title={`Hook #${index + 1}`}
                  content={hook}
                  onRegenerate={() => handleGenerate(undefined, true)}
                  isRegenerating={regenerating}
                />
              ))}
            </div>
          </motion.div>
        )}
      </div>

      {/* Trending Hooks Sidebar */}
      <div className="lg:col-span-3 bg-white/[0.005] border border-white/5 rounded-3xl p-5 backdrop-blur-xl shadow-2xl bento-card">
        <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest mb-4 flex items-center gap-2 font-mono">
          <Flame className="h-4 w-4 text-rose-500 animate-pulse" /> TRENDING TELEMETRY
        </span>
        <p className="text-zinc-500 text-xs mb-4 leading-relaxed font-sans font-medium">
          Click to load preset copy topics directly into the generation pipeline:
        </p>

        <div className="space-y-3">
          {TRENDING_HOOKS.map((item, idx) => (
            <Tilt
              key={idx}
              glareEnable={true}
              glareMaxOpacity={0.08}
              glareColor="#ffffff"
              glarePosition="all"
              tiltMaxAngleX={4}
              tiltMaxAngleY={4}
              className="rounded-2xl"
            >
              <button
                onClick={() => handleSelectTrending(item)}
                className="w-full text-left p-3.5 rounded-2xl bg-white/[0.015] hover:bg-white/[0.04] border border-white/5 hover:border-violet-500/20 transition-all cursor-pointer group active:scale-[0.98] block"
              >
                <div className="text-[9px] text-violet-400 font-bold font-mono mb-2 flex items-center gap-1.5 uppercase tracking-wider">
                  <FileText className="h-3 w-3" /> {item.topic}
                </div>
                <p className="text-zinc-300 text-[11px] leading-snug font-sans group-hover:text-white transition-colors">
                  &quot;{item.text}&quot;
                </p>
              </button>
            </Tilt>
          ))}
        </div>
      </div>

    </div>
  );
}
